#!/usr/bin/env bash

# Tries to figure out where the mkosi build directory is, and, if the directory
# could be found, executes mkosi to build all images

set -euo pipefail

looks_like_mkosi_dir() {
    [[ -d "${1:?whoopsie}" ]] && { [[ -f "${1}/mkosi.default" ]] || [[ -d "${1}/mkosi.files" ]] ; }
}

if [[ -z "${MKOSI_DIR:-}" ]]; then
    candidates=()
    toplevel=''

    if command -v git &>/dev/null && toplevel="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        candidates+=("${toplevel}/mkosi")
    fi

    if toplevel="$(readlink -f "${0%/*}/../mkosi")"; then
        candidates+=("${toplevel}/mkosi")
    fi

    candidates+=(/vagrant/mkosi /mkosi "$(pwd -P)")

    for candidate in "${candidates[@]}"; do
        if looks_like_mkosi_dir "$candidate"; then
            MKOSI_DIR="$candidate"
            break
        fi
    done
fi

if [[ -z "${MKOSI_DIR:-}" ]]; then
    echo 1>&2 "Unable to find mkosi directory; please set MKOSI_DIR."
    exit 1
fi

cd "$MKOSI_DIR" || exit

if (( $# < 1 )) && [[ -d "${MKOSI_DIR}/mkosi.files" ]]; then
    set -- -a
fi

exec mkosi "$@"
