#!/usr/bin/env bash

TRAVIS_BUILD_DIR="${TRAVIS_BUILD_DIR:-$(pwd -P)}"
TRAVIS_BUILD_DIR_BIND_DEST="${TRAVIS_BUILD_DIR_BIND_DEST:-/vagrant}"

exec docker run \
    --detach \
    --rm \
    --privileged \
    --cap-add SYS_ADMIN \
    -e ANSIBLE \
    -e ANSIBLE_DEBUG \
    -e CI \
    -e TRAVIS \
    -e TRAVIS_BRANCH \
    -e TRAVIS_JOB_ID \
    -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR_BIND_DEST}" \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --tmpfs /tmp:exec \
    --tmpfs /run:exec \
    "$@"
