#!/bin/sh

# Adapted from:
# https://github.com/kinvolk/kube-spawn/blob/692e9a03bace5afe3e7bdcf605b3bf863526745b/pkg/bootstrap/node.go

set -eu

MACHINE_MOUNT_PATH="${MACHINE_MOUNT_PATH:-/var/lib/machines}"
MACHINE_RAW_PATH="${MACHINE_RAW_PATH:-${MACHINE_MOUNT_PATH}.raw}"
MACHINE_POOL_SIZE="${MACHINE_POOL_SIZE:-10G}"

if [ -e "$MACHINE_RAW_PATH" ] && ! machinectl set-limit "$MACHINE_POOL_SIZE"; then
    umount "$MACHINE_MOUNT_PATH" || {
        case "$?" in
            32)
                :
                ;;
            *)
                exit $?
                ;;
        esac
    }

    qemu-img resize -f raw "$MACHINE_RAW_PATH" "$MACHINE_POOL_SIZE"
    mount -t btrfs -o loop "$MACHINE_RAW_PATH" "$MACHINE_MOUNT_PATH"
    btrfs filesystem resize max "$MACHINE_MOUNT_PATH"
    btrfs quota disable "$MACHINE_MOUNT_PATH"
fi
